#import "../deps.typ": radishom
#import radishom: *


#let (N, S, W, E, NW, NE, SW, SE) = dirs

#let corner-radius = 0.2
#let pin-round = pin.with(corner-radius: corner-radius)

#let lines = (
  line(
    id: "1",
    color: rgb("#009ace"),
    start-date: datetime(year: 2000, month: 4, day: 18),
    open-date: datetime(year: 2005, month: 5, day: 15),

    pin(x: 4.5, y: 11., cfg: "L1-N"),
    station("Baguazhoudaqiaonan", [BAGUAZHOUDAQIAONAN], anchor: W, logo-anchor: S),
    station("Badoushan", [BADOUSHAN], x: 3.),
    pin-round(x: 2.),
    station("Yanziji", [YANZIJI], y: 10.),
    station("Jixiang'an", [JIXIANG'AN]),
    station("Xiaozhuang", [XIAOZHUANG]),
    pin(y: 7., cfg: none),
    station("Maigaoqiao", [MAIGAOQIAO], y: 7., logo-anchor: SE),
    pin-round(y: 6.5),
    station("Hongshan Zoo", [HONGSHAN ZOO], y: 6.1, anchor: SE),
    station("Nanjing Railway Station", [NANJING RAILWAY STATION], anchor: E),
    pin-round(x: 0., d: SW),
    station("Xinmofanmalu", [XINMOFANMALU], y: 4),
    station("Xuanwumen", [XUANWUMEN]),
    station("Gulou", [GULOU]),
    station("Zhujianglu", [ZHUJIANGLU], alt: ("Ditie Dasha", [])),
    station("Xinjiekou", [XINJIEKOU]),
    station("Zhangfuyuan", [ZHANGFUYUAN]),
    station("Sanshanjie", [SANSHANJIE], y: -2.),
    pin-round(y: -3.5),
    station("Zhonghuamen", [ZHONGHUAMEN], y: -4.),
    station("Andemen", [ANDEMEN], y: -5.25),
    pin-round(x: -2., d: SW),
    station("Tianlongsi", [TIANLONGSI], y: -6.5),
    pin-round(y: -7.),
    station("Ruanjiandadao", [RUANJIANDADAO], x: -1.),
    station("Huashenmiao", [HUASHENMIAO], x: 0.),
    pin-round(x: 1. + 0.1),
    station("Nanjing South Railway Station", [NANJING SOUTH RAILWAY STATION], y: -8., anchor: NW),
    pin-round(y: -8.5),
    pin-round(x: 2.5),
    station("Shuanglongdadao", [SHUANGLONGDADAO], y: -9.),
    station("Hedingqiao", [HEDINGQIAO]),
    station("Shengtailu", [SHENGTAILU], y: -11.),
    station("Baijiahu", [BAIJIAHU], y: -12.75),
    pin-round(y: -13.),
    station("Xiaolongwan", [XIAOLONGWAN], anchor: N),
    station("Zhushanlu", [ZHUSHANLU]),
    station("Tianyindadao", [TIANYINDADAO], x: 6.),
    station("Longmiandadao", [LONGMIANDADAO], x: 7.),
    pin-round(x: 7.5),
    station("Nmu/jiett", [NMU/JIETT]),
    station("Njci", [NJCI]),
    station("Cpu", [CPU], logo-anchor: NW),
    pin(y: -15., d: SE),
  ),
  line(
    id: "2",
    color: rgb("#a6093d"),
    start-date: datetime(year: 2005, month: 12, day: 28),
    open-date: datetime(year: 2010, month: 5, day: 28),

    pin(
      x: -10.0,
      y: -8.0,
      cfg: "L2-W",
      start-date: datetime(year: 2018, month: 9, day: 2),
      open-date: datetime(year: 2021, month: 12, day: 28),
    ),
    station("Yuzui", [YUZUI], marker-rotation: 90deg, logo-anchor: SE),
    station("Tiaobaojie", [TIAOBAOJIE]),
    station("Qinglianjie", [QINGLIANJIE], anchor: N, x: -8.25),
    station("Luotanglu", [LUOTANGLU], anchor: NW),
    pin-round(x: -6.5 + 0.15),
    pin(x: -5.8, d: NE, cfg: none, start-date: auto, open-date: auto),
    station("Youfangqiao", [YOUFANGQIAO], r: 0, anchor: W, logo-anchor: NE),
    pin-round(x: -5.0, d: NE),
    station("Yuantong", [YUANTONG], y: -5.75, anchor: NE),
    pin-round(x: -6.25, d: NW),
    station("Yuantong", [YUANTONG]),
    station("Olympic Stadium East", [OLYMPIC STADIUM EAST], y: -3.75),
    pin-round(x: -4.5, d: NE),
    station("Xinglongdajie", [XINGLONGDAJIE], y: -3.),
    station("Xinglongdajie", [XINGLONGDAJIE], y: -2, cfg-not: "no-jqmdj"),
    pin-round(y: -1),
    station("Yunjinlu", [YUNJINLU], alt: ("Jinianguan", [JINIANGUAN])),
    pin-round(x: -3.25),
    station("Mochouhu", [MOCHOUHU], x: -3.),
    pin-round(y: 0., d: NE),
    station("Hanzhongmen", [HANZHONGMEN], x: -2.),
    station("Shanghailu", [SHANGHAILU], alt: ("Shengzhongyiyuan", [SHENGZHONGYIYUAN])),
    station("Xinjiekou", [XINJIEKOU]),
    station("Daxinggong", [DAXINGGONG]),
    station("Xi'anmen", [XI'ANMEN], x: 2., anchor: N),
    station("Minggugong", [MINGGUGONG]),
    station("Muxuyuan", [MUXUYUAN], x: 5.),
    station("Xiamafang", [XIAMAFANG]),
    station("Xiaolingwei", [XIAOLINGWEI], x: 7.),
    station("Zhonglingjie", [ZHONGLINGJIE], x: 8.),
    pin-round(x: 8.5),
    pin-round(y: 1. + 0.1, d: NE),
    station("Maqun", [MAQUN], x: 10.0),
    pin-round(x: 11.),
    station("Jinmalu", [JINMALU], anchor: E, y: 3.),
    pin-round(y: 3.75),
    station("Xianhemen", [XIANHEMEN], x: 11.5),
    station("Xuezelu", [XUEZELU], alt: ("Yadongcheng", [YADONGCHENG])),
    station("Xianlinzhongxin", [XIANLINZHONGXIN]),
    station("Yangshangongyuan", [YANGSHANGONGYUAN], x: 14.0),
    pin-round(y: 7., d: NE),
    station("Nju Xianlin Campus", [NJU XIANLIN CAMPUS], x: 15.5),
    station("Jingtianlu", [JINGTIANLU], x: 17., anchor: N, logo-anchor: S),
    pin(x: 17., cfg: "L2-EE", start-date: none),
    pin-round(x: 18.4),
    station("Xianlinhu", [XIANLINHU], anchor: E, logo-anchor: NE),
    pin(y: 8.),
  ),
  line(
    id: "3",
    color: rgb("#009a44"),
    start-date: datetime(year: 2010, month: 1, day: 10),
    open-date: datetime(year: 2015, month: 4, day: 1),

    pin(x: -11, y: 12.),
    station("Linchang", [LINCHANG], logo-anchor: N),
    station("Xinghuolu", [XINGHUOLU], x: -9.5),
    station("Seu Chengxian College", [SEU CHENGXIAN COLLEGE], anchor: N),
    station("Taifenglu", [TAIFENGLU]),
    station("Tianruncheng", [TIANRUNCHENG], x: -6.),
    pin-round(x: -5.5, y: 12.),
    station("Liuzhoudonglu", [LIUZHOUDONGLU]),
    station("Shangyuanmen", [SHANGYUANMEN],
      x: -2.25,
      open-date: datetime(year: 2015, month: 10, day: 18),
    ),
    station("Wutangguangchang", [WUTANGGUANGCHANG], anchor: E),
    station("Xiaoshi", [XIAOSHI]),
    station("Nanjing Railway Station", [NANJING RAILWAY STATION]),
    pin-round(y: 4.5, d: SE),
    station("Nfu/xinzhuang", [NFU/XINZHUANG], y: 4.),
    pin-round(y: 3.5),
    pin-round(x: 1., d: SW),
    station("Jimingsi", [JIMINGSI], y: 2.),
    station("Fuqiao", [FUQIAO]),
    station("Daxinggong", [DAXINGGONG]),
    station("Changfujie", [CHANGFUJIE]),
    station("Fuzimiao", [FUZIMIAO], y: -2.),
    pin-round(y: -2.25),
    pin-round(x: 1.5, d: SE),
    station("Wudingmen", [WUDINGMEN], y: -3.),
    pin-round(y: -3.75),
    station("Yuhuammen", [YUHUAMMEN], y: -4.),
    pin-round(x: 2., d: SE),
    station("Kazimen", [KAZIMEN]),
    station("Daminglu", [DAMINGLU], anchor: NW),
    pin-round(y: -7.5),
    station("Mingfaguangchang", [MINGFAGUANGCHANG]),
    pin-round(x: 1.),
    station("Nanjing South Railway Station", [NANJING SOUTH RAILWAY STATION], y: -8.),
    station("Hongyundadao", [HONGYUNDADAO], y: -9.),
    station("Shengtaixilu", [SHENGTAIXILU], y: -11.),
    station("Tianyuanxilu", [TIANYUANXILU], y: -13.),
    pin-round(y: -14.),
    station("Jiulonghu", [JIULONGHU]),
    pin-round(x: 3.),
    station("Chengxindadao", [CHENGXINDADAO], y: -15.),
    station("Seu Jiulonghu Campus", [SEU JIULONGHU CAMPUS]),
    station("Mozhoudonglu", [MOZHOUDONGLU], r: 1., logo-anchor: E),
    pin(
      y: -17.,
      cfg: "3-3",
      start-date: datetime(year: 2021, month: 5, day: 21),
      open-date: datetime(year: 2025, month: 12, day: 19),
    ),
    station("Shangqinhuaixi", [SHANGQINHUAIXI], r: 0.5),
    station("Moling", [MOLING], logo-anchor: E),
    pin(y: -19.),
  ),
  line(
    id: "4",
    color: rgb("#7d55c7"),
    start-date: datetime(year: 2011, month: 12, day: 27),
    open-date: datetime(year: 2017, month: 1, day: 18),

    pin(x: -12., y: 13., cfg: "L4-3", start-date: none, open-date: none),
    station("Yujiaying", [YUJIAYING], logo-anchor: E),
    station("Nanjing North Railway Station", [NANJING NORTH RAILWAY STATION], anchor: NW),
    station("Huguocun", [HUGUOCUN], y: 11.0),
    pin-round(y: 10.75),
    pin-round(y: 9.25, d: SE),
    station("Longzhigu", [LONGZHIGU]),
    pin-round(y: 8.5),
    pin(
      x: -10.75,
      d: SW,
      cfg: "L4-2",
      start-date: datetime(year: 2021, month: 2, day: 1),
      open-date: none,
    ),
    station("Zhenzhuquandong", [ZHENZHUQUANDONG], r: 0., anchor: SE, logo-anchor: SE),
    station("Ruilongjiaoyegongyuan", [RUILONGJIAOYEGONGYUAN], anchor: SE),
    pin-round(y: 7.25, d: SW),
    station("Shifosi", [SHIFOSI], y: 7.),
    station("Dingshandajie", [DINGSHANDAJIE]),
    station("Jiangbeishangwuqu", [JIANGBEISHANGWUQU], anchor: W),
    station("Jiangbeishiminzhongxin", [JIANGBEISHIMINZHONGXIN], y: 5.25),
    station("Jiangxinzhouwei", [JIANGXINZHOUWEI], y: 2.25),
    pin-round(x: -6.5, y: 2.),
    pin(x: -4.5, y: 2., cfg: none, start-date: auto, open-date: auto),
    station("Longjiang", [LONGJIANG], logo-anchor: E),
    station("Caochangmen", [CAOCHANGMEN]),
    station("Yunnanlu", [YUNNANLU]),
    station("Gulou", [GULOU]),
    station("Jimingsi", [JIMINGSI]),
    station("Jiuhuashan", [JIUHUASHAN], x: 2., anchor: N),
    pin-round(x: 2.5),
    station("Gangzicun", [GANGZICUN], y: 2.75),
    station("Jiangwangmiao", [JIANGWANGMIAO], x: 4.5),
    station("Wangjiawan", [WANGJIAWAN], x: 5.25),
    pin-round(x: 5.5, d: NE),
    station("Jubaoshan", [JUBAOSHAN], x: 8.0),
    pin-round(x: 9.5),
    station("Xuzhuang", [XUZHUANG], x: 10.),
    pin-round(x: 11. + 0.1, d: SE),
    station("Jinmalu", [JINMALU], y: 3.),
    pin-round(y: 2.),
    pin-round(dx: 0.5),
    pin-round(dx: 1., d: NE),
    station("Huitonglu", [HUITONGLU], x: 13.),
    station("Lingshan", [LINGSHAN], x: 14.),
    station("Dongliu", [DONGLIU], x: 16.),
    pin-round(x: 18.0),
    station("Mengbei", [MENGBEI], x: 18.25),
    pin-round(dx: 1.0, d: NE),
    station("Xiganghuashu", [XIGANGHUASHU], dy: 0.75),
    pin-round(y: 7.0),
    pin-round(dx: -0.4, d: NW),
    station("Xianlinhu", [XIANLINHU], r: 1.0, logo-anchor: SW),
    pin(y: 8., cfg: "L4-4", start-date: none),
    pin-round(y: 8.5),
    pin-round(x: 18.25, d: NW),
    station("Baixiang", [BAIXIANG], y: 9.5, anchor: E),
    pin-round(y: 10.0),
    pin-round(x: 18.5, d: NE),
    station("Guanyaoshanlu", [GUANYAOSHANLU], anchor: SE),
    pin-round(y: 11.5),
    station("Huaqiaocheng", [HUAQIAOCHENG], x: 19.0),
    station("Huanlegu", [HUANLEGU], logo-anchor: N),
    pin(x: 20.0),
  ),
  line(
    id: "5",
    color: rgb("#fdda24"),
    optional: true,
    start-date: datetime(year: 2016, month: 12, day: 28),
    open-date: datetime(year: 2024, month: 3, day: 31),

    pin(x: -4.25, y: 7., cfg: "L5-N", open-date: datetime(year: 2025, month: 8, day: 6)),
    station("Fangjiaying", [FANGJIAYING], logo-anchor: S),
    station("Nanjingxizhan", [NANJINGXIZHAN], anchor: SE, y: 6.375),
    pin-round(x: -5., d: SW),
    station("Jinghaisi", [JINGHAISI], y: 5.75, anchor: E),
    pin-round(y: 5.),
    station("Xiaguan", [XIAGUAN], anchor: SW),
    pin-round(x: -3.5),
    station("Yancangqiao", [YANCANGQIAO], x: -3.375),
    station("Fujianlu", [FUJIANLU]),
    station("Hongqiao", [HONGQIAO]),
    station("Qingchunguangchang", [QINGCHUNGUANGCHANG], x: -1.5, alt: ("Shanxilu", [SHANXILU])),
    pin-round(x: -1., d: SE),
    station("Yunnanlu", [YUNNANLU]),
    station("Wutaishan", [WUTAISHAN]),
    station("Shanghailu", [SHANGHAILU]),
    station("Chaotiangong", [CHAOTIANGONG]),
    pin-round(y: -2.),
    station("Sanshanjie", [SANSHANJIE]),
    station("Fuzimiao", [FUZIMIAO]),
    station("Tongjimen", [TONGJIMEN], x: 2., anchor: N),
    station("Guanghuamen", [GUANGHUAMEN]),
    pin-round(x: 4.5),
    station("Shimenkan", [SHIMENKAN]),
    station("Qiqiaoweng", [QIQIAOWENG], y: -4.),
    station("Dajiaochang", [DAJIAOCHANG]),
    station("Shenjiying", [SHENJIYING], y: -7.),
    station("Dongshanxiangzhangyuan", [DONGSHANXIANGZHANGYUAN], y: -9.),
    pin(y: -10., cfg: "L5-S", open-date: auto),
    station("Wenjinglu", [WENJINGLU], r: 0.),
    station("Dongshan", [DONGSHAN]),
    station("Xintinglu", [XINTINGLU]),
    station("Zhushanlu", [ZHUSHANLU]),
    station("Keninglu", [KENINGLU]),
    pin-round(y: -15.),
    station("Qianzhuang", [QIANZHUANG], x: 4., anchor: N),
    station("Chengxindadao", [CHENGXINDADAO]),
    pin-round(x: 2.5),
    pin-round(y: -16.),
    station("Jiulonghunan", [JIULONGHUNAN], x: 1.),
    station("Jiyindadao", [JIYINDADAO], logo-anchor: SE),
    pin(x: -0.5),
  ),
  line(
    id: "6",
    color: rgb("#4bbbb4"),
    optional: true,
    start-date: datetime(year: 2019, month: 12, day: 28),

    pin(x: 1. + 0.05, y: -8. + 0.1),
    station("Nanjing South Railway Station", [NANJING SOUTH RAILWAY STATION], x: 1.),
    pin-round(x: 3.5),
    station("Jiagang", [JIAGANG], y: -7.),
    station("Jichangpaodaojiuzhi", [JICHANGPAODAOJIUZHI], anchor: NE),
    station("Shizhongyiyuan", [SHIZHONGYIYUAN]),
    station("Yingtiandongjie", [YINGTIANDONGJIE]),
    station("Zhongheqiao", [ZHONGHEQIAO]),
    station("Guanghuamen", [GUANGHUAMEN]),
    station("Minggugong", [MINGGUGONG]),
    station("Fuguishan", [FUGUISHAN], y: 1.5),
    pin-round(y: 2.),
    pin-round(y: 2.5 - 0.07, d: NW),
    station("Gangzicun", [GANGZICUN]),
    pin-round(x: 4., d: NE),
    pin-round(y: 4.),
    station("Huayuanlu", [HUAYUANLU], y: 4.5),
    pin-round(x: 3., d: NW),
    station("Hongshanxincheng", [HONGSHANXINCHENG], y: 6.),
    pin-round(y: 6.5),
    station("Yingyuannanlu", [YINGYUANNANLU], alt: ("Hongshan", [HONGSHAN])),
    pin-round(x: 4., d: NE),
    station("Wanshou", [WANSHOU]),
    pin-round(y: 10.),
    station("Yanjiangxincheng", [YANJIANGXINCHENG], x: 4.5),
    station("Xingxuelu", [XINGXUELU], x: 6.),
    station("Xingzhijie", [XINGZHIJIE]),
    station("Shiyueguangchang", [SHIYUEGUANGCHANG], x: 9.5, anchor: S),
    pin-round(x: 11.0),
    pin-round(dy: 0.5),
    station("Jinlingshihua", [JINLINGSHIHUA], x: 12.5),
    station("Qixiashan", [QIXIASHAN], r: 1.0, logo-anchor: NW),
    pin(x: 15., cfg: "L6-E", start-date: none),
    pin-round(x: 18.0),
    pin-round(y: 10.0 + 0.1),
    station("Sheshan", [SHESHAN], r: 1.0, anchor: N, logo-anchor: S),
    pin(x: 19.0),
  ),
  line(
    id: "7",
    color: rgb("#4a7729"),
    optional: true,
    features: ("L7-full": ("L7-N", "L7-S", "L7-M")),
    start-date: datetime(year: 2017, month: 5, day: 16),
    open-date: datetime(year: 2022, month: 12, day: 28),

    pin(x: 10., y: 9., cfg: "L7-N"),
    station("Xianxinlu", [XIANXINLU],
      alt: ("Nanjingdongzhan", [NANJINGDONGZHAN]),
      marker-rotation: -45deg,
      logo-anchor: N,
      logo-offset: (0, -0.1),
    ),
    station("Yaohuamen", [YAOHUAMEN]),
    station("Yaohuaxincun", [YAOHUAXINCUN]),
    station("Dingjiazhuangnan", [DINGJIAZHUANGNAN], y: 6.5),
    pin-round(x: 7., y: 6.),
    station("Dingjiazhuang", [DINGJIAZHUANG], y: 7.),
    pin-round(x: 5., d: NW),
    station("Wanshou", [WANSHOU]),
    station("Xiaozhuang", [XIAOZHUANG]),
    station("Mufushan", [MUFUSHAN], x: 0.5),
    pin-round(x: -1.),
    station("Wutangguangchang", [WUTANGGUANGCHANG]),
    pin-round(x: -1.5, d: SW),
    station("Mufuxilu", [MUFUXILU], r: 1., anchor: E),
    pin(y: 7., cfg: "L7-M", open-date: datetime(year: 2024, month: 12, day: 28)),
    station("Zhongfulu", [ZHONGFULU], anchor: SE),
    pin-round(y: 5.5),
    station("Fujianlu", [FUJIANLU]),
    pin-round(x: -3., d: SW),
    station("Gupinggang", [GUPINGGANG], y: 3.25),
    station("Caochangmen", [CAOCHANGMEN]),
    station("Qingliangshan", [QINGLIANGSHAN]),
    station("Mochouhu", [MOCHOUHU]),
    station("Dashichating", [DASHICHATING]),
    station("Nanhu", [NANHU]),
    station("Yingtiandajie", [YINGTIANDAJIE], y: -3),
    pin(y: -3., cfg: "L7-S", open-date: datetime(year: 2023, month: 12, day: 28)),
    pin-round(y: -3.5),
    station("Mengdudajiedong", [MENGDUDAJIEDONG], y: -4.0),
    station("Xinchengkejiyuan", [XINCHENGKEJIYUAN]),
    station("Zhongsheng", [ZHONGSHENG]),
    station("Jialingjiangdongjie", [JIALINGJIANGDONGJIE], y: -5.75),
    pin-round(y: -6.25, d: SW),
    pin-round(dx: -0.75),
    station("Yongchulu", [YONGCHULU]),
    pin-round(x: -7.5, d: SW),
    station("Taiqinglu", [TAIQINGLU], y: -7.5),
    station("Luotanglu", [LUOTANGLU]),
    pin-round(y: -9.0 + 0.14),
    station("Xishanqiao", [XISHANQIAO], logo-anchor: SE),
    pin(y: -9.5 + 0.07, d: SW),
  ),
  line(
    id: "8",
    color: rgb("#ab2328"),
    optional: true,

    pin(x: -0.5, y: -4., cfg: none),
    station("Zhonghuamen", [ZHONGHUAMEN]),
    station("Yuhuammen", [YUHUAMMEN]),
    pin-round(x: 2.25),
    station("Kanganli", [KANGANLI]),
    pin-round(x: 3.25, d: NE),
    station("Zhongheqiao", [ZHONGHEQIAO]),
    station("Shimenkan", [SHIMENKAN]),
    station("Shenglicun", [SHENGLICUN], marker-rotation: 90deg),
    pin-round(x: 6.5),
    station("Shuangbaigang", [SHUANGBAIGANG], x: 7.25),
    pin-round(dy: 1., d: NE),
    station("Cangbomen", [CANGBOMEN], x: 8.25),
    pin-round(x: 8.5),
    pin-round(x: 9., d: SE),
    station("Jiannan", [JIANNAN]),
    pin-round(x: 10.),
    station("Qilinshengtaigongyuan", [QILINSHENGTAIGONGYUAN], y: -2.0),
    pin-round(x: 11., d: NE),
    station("Tianchenglu", [TIANCHENGLU]),
    pin-round(x: 12.),
    station("Dinglin", [DINGLIN]),
    pin-round(x: 13., d: NE),
    station("Zhijialu", [ZHIJIALU]),
    station("Qilinmen", [QILINMEN]),
    pin-round(y: 2.),
    pin-round(x: 14.),
    station("Lingshan", [LINGSHAN]),
    pin-round(y: 5.5),
    station("Xianlinzhongxin", [XIANLINZHONGXIN]),
    pin-round(x: 13., d: NW),
    pin-round(y: 8.),
    station("Wenlanlu", [WENLANLU]),
    pin-round(y: 9.25, d: NW),
    station("Xianlinzhan", [XIANLINZHAN]),
    pin-round(x: 10.75, d: SW),
    station("Xianxinlu", [XIANXINLU]),
    pin-round(x: 9.5, d: NW),
    station("Shiyueguangchang", [SHIYUEGUANGCHANG], logo-anchor: NE),
    pin(y: 10.),
  ),
  line(
    id: "9",
    color: rgb("#fa4616"),
    optional: true,
    start-date: datetime(year: 2020, month: 3, day: 8),

    pin(x: 3. - 0.1, y: 6.),
    station("Hongshanxincheng", [HONGSHANXINCHENG], logo-anchor: NE),
    pin-round(y: 5.),
    station("Hongshanlu", [HONGSHANLU], x: 2., alt: ("Caohoucun", [CAOHOUCUN])),
    pin-round(x: 1.5 - 0.15),
    station("Nanjing Railway Station", [NANJING RAILWAY STATION]),
    pin-round(y: 6., d: NW),
    station("Zhongyangmen", [ZHONGYANGMEN]),
    station("Zhongfulu", [ZHONGFULU]),
    station("Sipingluguangchang", [SIPINGLUGUANGCHANG]),
    pin-round(x: -4.5),
    station("Xiaguan", [XIAGUAN]),
    station("Baiyunting", [BAIYUNTING]),
    station("Sanchahe", [SANCHAHE]),
    station("Longjiang", [LONGJIANG]),
    station("Guanziqiao", [GUANZIQIAO]),
    station("Jiangdongmen", [JIANGDONGMEN]),
    pin-round(y: -1.),
    station("Qingjiannanlu", [QINGJIANNANLU], dx: -1.0),
    pin-round(dx: -2.0),
    station("Shangxinhe", [SHANGXINHE], y: -1.25, anchor: SE),
    station("Lüboyuan", [LÜBOYUAN]),
    station("Jscpa/xianfagongyuan", [JSCPA/XIANFAGONGYUAN], r: 1.0, anchor: E, logo-anchor: NE),
    pin(y: -3.5, cfg: "L9-2", start-date: none),
    pin-round(y: -3.75),
    station("Mianhuadi", [MIANHUADI], y: -4.25, anchor: SE),
    station("Qingaocun", [QINGAOCUN], anchor: SE),
    station("Shuangzha", [SHUANGZHA], anchor: SE),
    station("Haixiacheng", [HAIXIACHENG], anchor: SE),
    station("Yuzuishidigongyuan", [YUZUISHIDIGONGYUAN], anchor: SE),
    station("Touguan", [TOUGUAN], y: -7.125, anchor: SE),
    pin-round(x: -10.0, d: SW),
    station("Yuzui", [YUZUI]),
    pin(y: -8.5, cfg: "L9-3", start-date: none),
    pin-round(y: -9.0),
    station("Zuqiuxiaozhen", [ZUQIUXIAOZHEN], anchor: NE),
    pin-round(y: -9.575, d: SE),
    station("Liucun", [LIUCUN], logo-anchor: SE),
    station("Fengjidadao", [FENGJIDADAO]),
    station("Fenghuidadao", [FENGHUIDADAO], y: -11.25),
    pin-round(x: -11.5, d: SW),
    station("Banqiaozhongxin", [BANQIAOZHONGXIN], y: -11.875),
    pin-round(y: -12.5),
    station("Banqiao", [BANQIAO], marker-rotation: 45deg),
    station("Lianhuahugongyuan", [LIANHUAHUGONGYUAN], anchor: W, marker-rotation: 45deg, logo-anchor: NW),
    pin(x: -9.5),
  ),
  line(
    id: "10",
    color: rgb("#b9975b"),
    optional: true,
    start-date: datetime(year: 2010, month: 1, day: 10),
    open-date: datetime(year: 2014, month: 7, day: 1),

    pin(x: -1.75 + 0.08, y: -5.25 - 0.08),
    station("Andemen", [ANDEMEN], r: 0.0, branch: true, logo-anchor: SE, logo-offset: (0.2, 0.1)),
    pin-round(x: -2.5, d: SW),
    pin-round(x: -3.75),
    station("Xiaohang", [XIAOHANG]),
    station("Zhongsheng", [ZHONGSHENG]),
    station("Yuantong", [YUANTONG]),
    pin-round(x: -6.25, d: NW),
    station("Olympic Stadium", [OLYMPIC STADIUM], y: -3.5),
    pin-round(y: -3.0, d: NE),
    station("Mengdudajie", [MENGDUDAJIE], y: -2.75),
    pin-round(y: -2.),
    station("Lüboyuan", [LÜBOYUAN]),
    pin-round(x: -7.0),
    station("Jiangxinzhou", [JIANGXINZHOU], x: -8.75),
    station("Linjiang/yogsp", [LINJIANG/YOGSP], x: -11.5),
    station("Pukouwanhuicheng", [PUKOUWANHUICHENG]),
    station("Nanjing Tech", [NANJING TECH]),
    pin-round(y: 5., d: NW),
    station("Longhualu", [LONGHUALU]),
    station("Wendelu", [WENDELU]),
    station("Yushanlu", [YUSHANLU], r: 1.0, cfg: none, logo-anchor: SE),
    pin(y: 2., d: SW, cfg: "L10-3", start-date: auto),
    station("Xinshenghe", [XINSHENGHE]),
    station("Kegongyuan", [KEGONGYUAN], logo-anchor: SE),
    pin(y: 0., d: SW, end: true),

    pin(
      x: -1.75 + 0.08,
      y: -5.25 - 0.08,
      cfg: "L10-2",
      start-date: datetime(year: 2020, month: 6, day: 2),
      open-date: datetime(year: 2025, month: 12, day: 19),
    ),
    pin-round(y: -5., d: NE),
    station("Gongqingtuanlu", [GONGQINGTUANLU], x: -0.5, anchor: N, branch: true),
    station("Yuhuatai", [YUHUATAI], x: 0.5, anchor: N),
    station("Kazimen", [KAZIMEN]),
    pin-round(x: 2.25),
    pin-round(x: 3.25, d: SE),
    station("Jichangpaodaojiuzhi", [JICHANGPAODAOJIUZHI]),
    pin-round(x: 4.),
    station("Dajiaochang", [DAJIAOCHANG]),
    station("Chengtiandadao", [CHENGTIANDADAO], x: 5.0),
    station("Gaoqiaomen", [GAOQIAOMEN], x: 5.75),
    pin-round(x: 6., d: NE),
    station("Yangzhuang", [YANGZHUANG], x: 7.5),
    station("Shiyanglu", [SHIYANGLU], alt: ("Wangwuzhuang", [WANGWUZHUANG])),
    station("Dongqilu", [DONGQILU], logo-anchor: NW),
    pin(x: 9.5),
  ),
  line(
    id: "11",
    color: rgb("#ef426f"),
    optional: true,
    start-date: datetime(year: 2021, month: 11, day: 30),

    pin(x: -5., y: 12.5),
    station("Puzhoulu", [PUZHOULU], logo-anchor: S),
    station("Liuzhoudonglu", [LIUZHOUDONGLU]),
    pin-round(y: 11.),
    station("Mingbinlu", [MINGBINLU], x: -5.25),
    station("Changjiangdaqiaobei", [CHANGJIANGDAQIAOBEI]),
    station("Liuzhounanlu", [LIUZHOUNANLU]),
    station("Pudonglu", [PUDONGLU]),
    station("Xinmalu", [XINMALU]),
    station("Njrts", [NJRTS]),
    station("Guangxigengdajie", [GUANGXIGENGDAJIE]),
    station("Jiangbeishangwuqu", [JIANGBEISHANGWUQU]),
    station("Qilihe", [QILIHE]),
    station("Linchulu", [LINCHULU]),
    station("Pukouwanhuicheng", [PUKOUWANHUICHENG]),
    station("Chengnanhe", [CHENGNANHE]),
    station("Jiangmiaolu", [JIANGMIAOLU]),
    station("Zhuoyuelu", [ZHUOYUELU]),
    station("Xingzhilu", [XINGZHILU]),
    station("Lüshuiwanlu", [LÜSHUIWANLU]),
    station("Xijiangkou", [XIJIANGKOU], y: -2),
    station("Maluowei", [MALUOWEI], logo-anchor: SE),
    pin(y: -3., d: SW),
  ),
  line(
    id: "12",
    color: rgb("#c87a30"),
    optional: true,

    pin(x: 11.0 - 0.1, y: 3.0),
    station("Jinmalu", [JINMALU], logo-anchor: NE),
    pin-round(y: 1.5),
    pin-round(x: 12.0),
    station("Baishuiqiao", [BAISHUIQIAO]),
    pin-round(y: 0.5),
    station("Nanwanying", [NANWANYING]),
    station("Huagang", [HUAGANG]),
    pin-round(x: 10.0, d: SW),
    station("Qilinshengtaigongyuan", [QILINSHENGTAIGONGYUAN]),
    pin-round(x: 10.75, d: SE),
    station("Guanghualu", [GUANGHUALU]),
    pin-round(x: 9.5, d: SW),
    station("Dongqilu", [DONGQILU]),
    station("Yuantailu", [YUANTAILU]),
    station("Shangfang", [SHANGFANG]),
    pin-round(y: -9.0),
    station("Wananxilu", [WANANXILU]),
    pin-round(y: -11.0, d: SW),
    station("Jinbolu", [JINBOLU]),
    station("Dongshan", [DONGSHAN]),
    pin-round(x: 4.0),
    station("Yangjiawei", [YANGJIAWEI], anchor: E),
    pin-round(y: -12.5),
    station("Ximenzilu", [XIMENZILU]),
    pin-round(x: 2.5 + 0.1),
    station("Baijiahu", [BAIJIAHU]),
    pin-round(y: -13.0),
    station("Tianyuanxilu", [TIANYUANXILU]),
    pin-round(x: 0.0),
    station("Aitaolu", [AITAOLU]),
    pin-round(y: -14.0),
    station("Hhu/fochengxilu", [HHU/FOCHENGXILU], anchor: NW),
    station("Kanghoujie", [KANGHOUJIE]),
    station("Niushoushan", [NIUSHOUSHAN], logo-anchor: N),
    pin(x: -3.0),
  ),
  line(
    id: "13",
    // color: rgb("#007654"),
    color: rgb("#A6BE47"),
    optional: true,

    pin(x: -11.5, y: 6.),
    station("Guojijiankangshequ", [GUOJIJIANKANGSHEQU], logo-anchor: N),
    pin-round(dx: 1.0 - 0.14),
    station("Jiangbeishangwuqu", [JIANGBEISHANGWUQU]),
    station("Jiangbeishiminzhongxin", [JIANGBEISHIMINZHONGXIN]),
    pin-round(x: -9.0, d: SE),
    pin-round(y: 3.0),
    station("Jiangxinzhoubei", [JIANGXINZHOUBEI], x: -7.25),
    pin-round(x: -7.0, d: SE),
    station("Leshanlu", [LESHANLU], x: -5.25),
    station("Guanziqiao", [GUANZIQIAO]),
    station("Nenjianglu", [NENJIANGLU], anchor: N),
    station("Qingliangshan", [QINGLIANGSHAN]),
    station("Guangzhoulu", [GUANGZHOULU], alt: ("Shengrenminyiyuan", [SHENGRENMINYIYUAN]), anchor: N),
    station("Wutaishan", [WUTAISHAN]),
    station("Zhujianglu", [ZHUJIANGLU]),
    station("Fuqiao", [FUQIAO]),
    station("Mabiao", [MABIAO], x: 2.0),
    pin-round(x: 2.5),
    station("Jiefanglu", [JIEFANGLU], y: -0.5),
    pin-round(y: -1.0),
    station("Yueyahu", [YUEYAHU], x: 4.0),
    station("Houbiaoying", [HOUBIAOYING]),
    station("Nanjingnongyedaxue", [NANJINGNONGYEDAXUE], x: 6.0),
    pin-round(x: 6.5),
    station("Shenglicun", [SHENGLICUN]),
    pin-round(y: -3.5 + 0.14),
    station("Gaoqiaomen", [GAOQIAOMEN], logo-anchor: S, logo-offset: (-0.2, 0)),
    pin(dx: -0.8, d: SW),
  ),
  line(
    id: "16",
    // color: rgb("#ef7f1b"),
    color: rgb("#A8D19E"),
    optional: true,

    pin(x: 3.5, y: -6.0 + 0.1),
    station("Jichangpaodaojiuzhi", [JICHANGPAODAOJIUZHI], logo-anchor: NW),
    pin-round(x: 2.5),
    station("Daminglu", [DAMINGLU]),
    station("Yulanlu", [YULANLU], x: 1.5, anchor: SE),
    pin-round(y: -7.0 - 0.1, d: SW),
    station("Ruanjiandadao", [RUANJIANDADAO], x: -1.0),
    pin-round(x: -2.0),
    station("Ningshuanglu", [NINGSHUANGLU], y: -7.4, anchor: E),
    station("Tiexinqiao", [TIEXINQIAO]),
    station("Yinxingshanzhuang", [YINXINGSHANZHUANG], y: -9.5),
    pin-round(y: -10.0),
    station("Dadingfang", [DADINGFANG], x: -3.0),
    station("Meiyuannanlu", [MEIYUANNANLU]),
    station("Meixinlu", [MEIXINLU], x: -6.5),
    pin-round(x: -7.0),
    station("Xishanhuayuan", [XISHANHUAYUAN], dx: -0.5),
    station("Huaxinglu", [HUAXINGLU]),
    station("Xinchengdajie", [XINCHENGDAJIE]),
    station("Lianhuahugongyuan", [LIANHUAHUGONGYUAN]),
    station("Banqiaodong", [BANQIAODONG]),
    pin-round(x: -10.5, d: SW),
    station("Lüzhou", [LÜZHOU], dx: -0.5),
    station("Banqiaonan", [BANQIAONAN], marker-rotation: 45deg, logo-anchor: SE),
    pin(x: -12.0),
  ),
  line(
    id: "18",
    // color: rgb("#ee7852"),
    color: rgb("#FA9A85"),
    optional: true,

    pin(x: -12 - 0.1, y: 12, layer: -5),
    station("Nanjing North Railway Station", [NANJING NORTH RAILWAY STATION], logo-anchor: NE),

    pin-round(y: 11.0 - 0.3, corner-radius: 0.25),
    pin-round(x: -10.75, d: SE),
    pin-round(y: 8.75),
    station("Nanjingtiedaoxueyuan", [NANJINGTIEDAOXUEYUAN]),
    station("Xinhuajie", [XINHUAJIE], y: 6.25),
    pin-round(y: 3.25, d: SE),
    station("Gupinggang", [GUPINGGANG]),
    pin-round(x: -1.5),
    pin-round(y: 2.1, d: SE),
    pin-round(x: 0.25),
    station("Gulou", [GULOU]),
    station("Xinjiekou", [XINJIEKOU]),
    pin-round(y: -2.5),
    pin-round(dx: 0.25, d: SE),
    pin-round(y: -3.25),
    station("Zhonghuamen", [ZHONGHUAMEN]),
    pin-round(dx: -1.0, d: SW),
    pin-round(dy: -0.5),
    pin-round(x: 1.75),
    pin-round(y: -8.25),
    station("Nanjingnanzhan", [NANJINGNANZHAN]),
    pin-round(x: -0.25),
    station("Hhu/fochengxilu", [HHU/FOCHENGXILU]),
    pin-round(y: -16.25),
    pin-round(dx: 0.75, d: SE),
    station("Lukoudong", [LUKOUDONG], y: -18.0),
    pin-round(y: -19.0),
    station("Xiangyulunan", [XIANGYULUNAN]),
    pin-round(x: -1.0),
    pin-round(y: -20.0 - 0.1),
    station("Lukoujichangxi", [LUKOUJICHANGXI]),
    station("Lukoujichang", [LUKOUJICHANG], logo-anchor: N),
    pin(x: 1.0),
  ),
  line(
    id: "S1",
    color: rgb("#4bbbb4"),
    optional: true,
    start-date: datetime(year: 2011, month: 12, day: 27),
    open-date: datetime(year: 2014, month: 7, day: 1),

    pin(x: 1. + 0.05, y: -8 + 0.1),
    station("Nanjing South Railway Station", [NANJING SOUTH RAILWAY STATION]),
    pin-round(dx: -1.0),
    pin-round(x: -0.5, d: SW),
    station("Cuipingshan", [CUIPINGSHAN], y: -11., anchor: E),
    station("Hhu/fochengxilu", [HHU/FOCHENGXILU], y: -14.0, anchor: E),
    station("Jiyindadao", [JIYINDADAO]),
    station("Zhengfangzhonglu", [ZHENGFANGZHONGLU]),
    station("Xiangyulubei", [XIANGYULUBEI], alt: ("Ruyihu", [RUYIHU])),
    station("Xiangyulunan", [XIANGYULUNAN]),
    pin-round(y: -20.),
    station("Lukou International Airport", [LUKOU INTERNATIONAL AIRPORT], r: 1.),
    pin(
      dx: 1.5,
      d: E,
      cfg: "S1-E",
      start-date: datetime(year: 2016, month: 4, day: 8),
      open-date: datetime(year: 2018, month: 5, day: 26),
    ),
    station("Konggangxinchengjiangning", [KONGGANGXINCHENGJIANGNING], logo-anchor: N),
    pin(dx: 1.5),
  ),
  line(
    id: "S2",
    color: rgb("#ab2328"),
    optional: true,
    start-date: datetime(year: 2021, month: 3, day: 6),

    pin(x: -0.5, y: -4., cfg: none, start-date: none),
    station("Zhonghuamen", [ZHONGHUAMEN]),
    pin-round(x: -2.),
    station("Fengtainanlu", [FENGTAINANLU]),
    station("Xiaoxing", [XIAOXING]),
    pin-round(x: -5., d: SW),
    pin-round(x: -5.5),
    station("Youfangqiao", [YOUFANGQIAO]),
    pin(x: -8., y: -9.5, cfg: none, start-date: auto),
    station("Xishanqiao", [XISHANQIAO], r: 0.),
    station("Yuhuajingji Development Zone", [YUHUAJINGJI DEVELOPMENT ZONE]),
    station("Banqiao", [BANQIAO]),
    station("Banqiaonan", [BANQIAONAN]),
    station("Jiangningzhen", [JIANGNINGZHEN]),
    station("Jiangningbinjiang Development Zone", [JIANGNINGBINJIANG DEVELOPMENT ZONE]),
    station("Mulong", [MULONG]),
    station("Tongjing", [TONGJING]),
    pin-round(dy: -7., d: SW),
    station("Cihu", [CIHU], dy: -0.5),
    station("Hubeilu", [HUBEILU]),
    station("Hunanlu", [HUNANLU]),
    station("Yushandonglu", [YUSHANDONGLU]),
    station("Jiuhualu", [JIUHUALU]),
    station("Caishihe", [CAISHIHE]),
    station("Dangtu East Railway Station", [DANGTU EAST RAILWAY STATION]),
    station("Dangtunan", [DANGTUNAN], logo-anchor: N),
    pin(dy: -6.5),
  ),
  line(
    id: "S3",
    color: rgb("#b06c96"),
    optional: true,
    start-date: datetime(year: 2012, month: 12, day: 27),
    open-date: datetime(year: 2017, month: 12, day: 6),

    pin(x: 1. + 0.05, y: -8),
    station("Nanjing South Railway Station", [NANJING SOUTH RAILWAY STATION]),
    station("Jingmingjiayuan", [JINGMINGJIAYUAN], x: -0.5),
    station("Tiexinqiao", [TIEXINQIAO]),
    station("Chunjianglu", [CHUNJIANGLU]),
    station("Jiaxi", [JIAXI]),
    pin-round(x: -5.25),
    station("Youfangqiao", [YOUFANGQIAO]),
    station("Yongchulu", [YONGCHULU]),
    pin-round(x: -7.375, d: NW),
    station("Pingliangdajie", [PINGLIANGDAJIE], y: -6.25),
    station("Wuhoujie", [WUHOUJIE], y: -6.75),
    pin-round(x: -8.5, d: SW),
    station("Gaomiaolu", [GAOMIAOLU], y: -7.5),
    pin-round(dy: -1.5),
    station("Tianbao", [TIANBAO], x: -9.25),
    station("Liucun", [LIUCUN], y: -10.0),
    pin-round(dy: -2.0, d: SW),
    pin-round(x: -18.5, d: NW),
    station("Maluowei", [MALUOWEI], x: -19.0),
    station("Lanhuatang", [LANHUATANG], x: -19.75),
    station("Shuanglong", [SHUANGLONG]),
    station("Shiqihe", [SHIQIHE]),
    station("Qiaolinxincheng", [QIAOLINXINCHENG]),
    station("Linshan", [LINSHAN]),
    station("Gaojiachong", [GAOJIACHONG], logo-anchor: SE),
    pin(dx: -5.5, d: SW, end: true),

    pin(x: 1.0, y: -8.0, cfg: "S3-E", start-date: none),
    pin-round(x: 4.0),
    station("Jinshenglu", [JINSHENGLU], anchor: E, branch: true),
    pin-round(dy: -1.0),
    station("Dongshanxiangzhangyuan", [DONGSHANXIANGZHANGYUAN]),
    pin-round(dx: 1.0),
    station("Huxilu", [HUXILU], dx: 1.0, alt: ("Tushan", [TUSHAN])),
    pin-round(x: 8.5, d: NE),
    station("Shangfanggongyeyuan", [SHANGFANGGONGYEYUAN], y: -5., anchor: E),
    station("Shiyanglu", [SHIYANGLU]),
    pin-round(y: -3.),
    pin-round(dx: 1.0 + 0.14),
    station("Qilinshengtaigongyuan", [QILINSHENGTAIGONGYUAN], y: -2.0),
    pin-round(y: -1.75, d: NE),
    pin-round(x: 13.5),
    station("Quanshuilu", [QUANSHUILU]),
    pin-round(dx: 1.0, d: NE),
    station("Zhongkeyuan", [ZHONGKEYUAN]),
    pin-round(y: 1.0 - 0.1),
    station("Dongjiaoxiaozhen", [DONGJIAOXIAOZHEN], x: 15.0),
    pin-round(x: 16.0),
    station("Dongliu", [DONGLIU]),
    station("Sanyanglu", [SANYANGLU], y: 4.5, anchor: E),
    pin-round(y: 5.0),
    pin-round(y: 5.5, d: NW),
    station("Nju Xianlin Campus", [NJU XIANLIN CAMPUS]),
    station("Jsbc", [JSBC], y: 9.0),
    pin-round(y: 9.5),
    pin-round(x: 12.0 - 0.14),
    station("Xianlin Railway Station", [XIANLIN RAILWAY STATION]),
    pin(dy: -0.7, d: SW),
  ),
  line(
    id: "S4",
    color: rgb("#ff661f"),
    optional: true,
    start-date: datetime(year: 2018, month: 12, day: 30),
    open-date: datetime(year: 2023, month: 6, day: 28),

    pin(x: -12. + 0.1, y: 12., cfg: "S4-2", start-date: none),
    station("Nanjing North Railway Station", [NANJING NORTH RAILWAY STATION], anchor: E),
    pin-round(dy: 1.5),
    station("Beidouchanyeyuan", [BEIDOUCHANYEYUAN]),
    pin-round(dx: -1., d: NW),
    station("Zhangbao", [ZHANGBAO]),
    pin-round(dx: -1. - 0.1),
    pin(dx: -0.5, cfg: none, start-date: auto),
    station("Chahe", [CHAHE], r: 0.),
    station("Chahexincheng", [CHAHEXINCHENG], dx: -1.0),
    station("Xiangguan", [XIANGGUAN], dx: -1.75, open-date: none),
    station("Shierliban", [SHIERLIBAN]),
    pin-round(dx: -4., d: NW),
    station("Shuikou", [SHUIKOU], dx: -0.5, open-date: none),
    station("Linlou", [LINLOU], dx: -1.5),
    pin-round(dx: -2.),
    station("Daiwangying", [DAIWANGYING]),
    pin-round(dy: -1.),
    station("Suchushangwuzhongxin", [SUCHUSHANGWUZHONGXIN], dy: -0.25),
    station("Danzi", [DANZI]),
    pin-round(dy: -1.5, d: SW),
    station("Chuzhouzhengwuzhongxin", [CHUZHOUZHENGWUZHONGXIN], dx: -0.5),
    station("Langyashan", [LANGYASHAN], dx: -1.5),
    pin-round(dx: -2.),
    station("Huaboyuan", [HUABOYUAN], dy: -0.5),
    station("Yaopu", [YAOPU], dy: -1.5),
    pin-round(dy: -2.),
    station("Chuzhou Railway Station", [CHUZHOU RAILWAY STATION], logo-anchor: N),
    pin(dy: -0.5, d: SE),
  ),
  line(
    id: "S5",
    color: rgb("#f5df4d"),
    optional: true,
    start-date: datetime(year: 2021, month: 12, day: 28),

    pin(x: 16.0 + 0.1, y: 3.0, cfg: "L5-S", start-date: none),
    station("Dongliu", [DONGLIU], logo-anchor: NW),
    pin-round(dy: 1.0),
    pin-round(dy: 1., d: NE),
    station("Luojiabian", [LUOJIABIAN], x: 17.5),
    pin-round(x: 18.5),
    pin(x: 18.5, y: 8., cfg: none, start-date: auto),
    station("Xianlinhu", [XIANLINHU], r: 0),
    pin-round(dy: 2.),
    station("Sheshan", [SHESHAN], dx: 0.5),
    pin-round(dx: 1.5),
    station("Jiangcheng", [JIANGCHENG]),
    station("Longtan", [LONGTAN], dx: 1.25),
    pin-round(dx: 1.5, d: NE),
    station("Huayuanyingfang", [HUAYUANYINGFANG], dx: 0.5),
    station("Longtanxincheng", [LONGTANXINCHENG]),
    station("Jingan", [JINGAN], dx: 2.5),
    pin-round(dx: 3.),
    station("Huangtiandang", [HUANGTIANDANG], dy: 0.5),
    station("Gumei", [GUMEI], dy: 3.),
    pin-round(dy: 3.5),
    station("Zhenzhou", [ZHENZHOU], dx: 0.5),
    station("Yizhengkeyunshuniu", [YIZHENGKEYUNSHUNIU]),
    station("Yizheng Development Zone", [YIZHENG DEVELOPMENT ZONE], dx: 2.5),
    station("Puxi", [PUXI], dx: 4.),
    pin-round(dx: 4.5),
    station("Xuelou", [XUELOU], anchor: E),
    station("Wenhuixilu", [WENHUIXILU], anchor: E),
    station("Yangzhouxi Railway Station", [YANGZHOUXI RAILWAY STATION], anchor: E, logo-anchor: S),
    pin(dy: 3.),
  ),
  line(
    id: "S6",
    color: rgb("#c98bdb"),
    optional: true,
    start-date: datetime(year: 2018, month: 12, day: 21),
    open-date: datetime(year: 2021, month: 12, day: 28),

    pin(x: 6.0, y: -1.0 + 0.1, cfg: "S6-W", start-date: none, open-date: none),
    station("Njau", [NJAU], logo-anchor: N),
    pin-round(x: 6.5 + 0.1, corner-radius: 0.3),
    pin-round(y: -1.5),
    station("Njust", [NJUST], x: 7.5),
    pin-round(x: 8.5),
    station("Gujiaying", [GUJIAYING], y: -0.5),
    pin-round(y: -0.25),
    station("Wukesong", [WUKESONG]),
    pin-round(y: 1.0, d: NE),
    pin(x: 10.0, y: 1., cfg: none, start-date: auto, open-date: auto),
    station("Maqun", [MAQUN], r: 0, logo-anchor: N),
    station("Baishuiqiao", [BAISHUIQIAO], x: 12.0),
    station("Qilinmen", [QILINMEN], x: 13.0),
    station("Dongjiaoxiaozhen", [DONGJIAOXIAOZHEN], x: 15.0),
    station("Guquan", [GUQUAN], x: 17.0),
    pin-round(dx: 7.5),
    pin-round(dx: 0.5, d: NE),
    station("Nanjingyuanrendong", [NANJINGYUANRENDONG]),
    pin-round(dx: 1.5),
    station("Tangshan", [TANGSHAN]),
    pin-round(dy: -0.75),
    pin-round(dx: -0.5, d: SW),
    station("Quandoudajie", [QUANDOUDAJIE]),
    pin-round(dy: -0.5),
    pin-round(dx: 0.25, d: SE),
    pin-round(dx: 0.75),
    station("Huangmei", [HUANGMEI]),
    pin-round(dx: 1., d: SE),
    station("Tongshijie", [TONGSHIJIE], dx: 1.5),
    pin-round(dx: 2.),
    station("Huayang", [HUAYANG]),
    station("Chongming", [CHONGMING]),
    station("Jurong", [JURONG], logo-anchor: N),
    pin(dy: -6.),
  ),
  line(
    id: "S7",
    color: rgb("#e89cae"),
    optional: true,
    start-date: datetime(year: 2016, month: 4, day: 8),
    open-date: datetime(year: 2018, month: 5, day: 26),

    pin(x: 2.5, y: -20.),
    station("Konggangxinchengjiangning", [KONGGANGXINCHENGJIANGNING]),
    pin-round(dx: 1.25),
    station("Zhetang", [ZHETANG], x: 4.),
    station("Konggangxinchenglishui", [KONGGANGXINCHENGLISHUI]),
    station("Qunli", [QUNLI], x: 5.),
    pin-round(dx: 1.5, d: SE),
    station("Wolonghu", [WOLONGHU], y: -21.75),
    station("Lishui", [LISHUI]),
    station("Zhongshanhu", [ZHONGSHANHU]),
    station("Xingzhuang", [XINGZHUANG]),
    station("Wuxiangshan", [WUXIANGSHAN], logo-anchor: N),
    pin(dy: -2.5),
  ),
  line(
    id: "S8",
    color: rgb("#ea7600"),
    optional: true,
    start-date: datetime(year: 2012, month: 6, day: 21),
    open-date: datetime(year: 2014, month: 8, day: 1),

    pin(
      x: -6.,
      y: 10.,
      cfg: "S8-N",
      start-date: datetime(year: 2018, month: 11, day: 10),
      open-date: datetime(year: 2022, month: 9, day: 30),
    ),
    station("Changjiangdaqiaobei", [CHANGJIANGDAQIAOBEI], logo-anchor: E),
    station("Maofangchanglu", [MAOFANGCHANGLU]),
    pin(dy: 1.25, d: NW, cfg: none, start-date: auto, open-date: auto),
    station("Taishanxincun", [TAISHANXINCUN], r: 0., logo-anchor: NW),
    pin-round(dy: 0.25, d: NW),
    station("Taifenglu", [TAIFENGLU]),
    station("Gaoxin Development Zone", [GAOXIN DEVELOPMENT ZONE]),
    station("Nuist", [NUIST]),
    station("Xiejiadian", [XIEJIADIAN], y: 14.25),
    pin-round(dy: 3.5),
    station("Dachang", [DACHANG], dx: 0.25),
    station("Getang", [GETANG]),
    station("Zhanglu", [ZHANGLU]),
    station("Huagongyuan", [HUAGONGYUAN]),
    station("Luhe Development Zone", [LUHE DEVELOPMENT ZONE]),
    station("Longchi", [LONGCHI]),
    station("Xiongzhou", [XIONGZHOU]),
    station("Fenghuangshangongyuan", [FENGHUANGSHANGONGYUAN]),
    station("Fangzhouguangchang", [FANGZHOUGUANGCHANG]),
    station("Shenqiao", [SHENQIAO]),
    station("Babaiqiao", [BABAIQIAO]),
    station("Jinniuhu", [JINNIUHU], logo-anchor: S),
    pin(dx: 6., d: NE),
  ),
  line(
    id: "S9",
    color: rgb("#f1b434"),
    optional: true,
    start-date: datetime(year: 2014, month: 1, day: 1),
    open-date: datetime(year: 2017, month: 12, day: 30),

    pin(x: -0.5, y: -19.),
    station("Xiangyulunan", [XIANGYULUNAN], logo-anchor: SE),
    pin-round(dx: -0.1, d: SW),
    pin-round(y: -20.75),
    station("Tongshan", [TONGSHAN]),
    pin-round(x: 0.5),
    station("Shijiao", [SHIJIAO], y: -21.),
    station("Mingjue", [MINGJUE], y: -22.),
    station("Tuanjiewei", [TUANJIEWEI], y: -24.),
    station("Gaochun", [GAOCHUN], logo-anchor: E),
    pin(y: -25.),
  ),
  line(
    id: "2-9",
    color: rgb("#ffc65f"),
    optional: true,

    pin(x: -4.5 - 0.1, y: -2),
    station("Jiqingmendajie", [JIQINGMENDAJIE], logo-anchor: SE),
    pin-round(y: -1 - 0.1),
    station("Qingjiangnanlu", [QINGJIANGNANLU]),
    pin(x: -5.5),
  ),
)
